apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-components/logging
    repoURL: https://gitlab.mareshq.com/gitops/mareshq/bee.git
    targetRevision: HEAD
    helm:
      skipCrds: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
