apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: argocd
spec:
  project: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: appsets/
    repoURL: https://github.com/vojtechmares/gitops.git
    targetRevision: HEAD
