apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.46.7
    helm:
      releaseName: argocd
      # !!! BUG !!!
      # See: https://github.com/argoproj/argo-cd/issues/15126
      # valuesObject:
      #   global:
      #     affinity:
      #       podAntiAffinity: hard

      #   redis-ha:
      #     enabled: true

      #   controller:
      #     replicas: 1

      #   repoServer:
      #     replicas: 2

      #   applicationSet:
      #     replicas: 2

      #   server:
      #     replicas: 2
      #     ingress:
      #       enabled: true
      #       hosts:
      #         - argocd.ops.mareshq.com
      #       ingressClassName: nginx
      #       annotations:
      #         cert-manager.io/cluster-issuer: letsencrypt-prod
      #         nginx.ingress.kubernetes.io/server-snippet: |
      #           proxy_ssl_verify off;
      #         nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      #       tls:
      #         - hosts:
      #             - argocd.ops.mareshq.com
      #           secretName: argocd-tls
      values: |
        global:
          affinity:
            podAntiAffinity: hard

        redis-ha:
          enabled: true

        controller:
          replicas: 1

        repoServer:
          replicas: 2

        applicationSet:
          replicas: 2

        server:
          replicas: 2
          ingress:
            enabled: true
            hosts:
              - argocd.ops.mareshq.com
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/server-snippet: |
                proxy_ssl_verify off;
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls:
              - hosts:
                  - argocd.ops.mareshq.com
                secretName: argocd-tls
