apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cherry-ingress-nginx
  namespace: argocd
spec:
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.0
    helm:
      releaseName: ingress-nginx
      valuesObject:
        ingressClassResource:
          default: true
        controller:
          kind: DaemonSet
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443
          config:
            allow-snippet-annotations: "true"
            generate-request-id: "true"
            use-proxy-protocol: "true"
