apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cherry-ingress-nginx
  namespace: argocd
spec:
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx/
    targetRevision: 4.8.0
    helm:
      releaseName: ingress-nginx
      # !!! BUG !!!
      # See: https://github.com/argoproj/argo-cd/issues/15126
      # valuesObject:
      #   ingressClassResource:
      #     default: true
      #   # TODO: enable proxy protocol
      #   controller:
      #     kind: DaemonSet
      #     updateStrategy:
      #       type: RollingUpdate
      #       rollingUpdate:
      #         maxUnavailable: 1
      #     service:
      #       # TODO: use Service .spec.type: NodePort
      #       type: ClusterIP
      #     hostPort:
      #       enabled: true
      #     config:
      #       allow-snippet-annotations: "true"
      #       generate-request-id: "true"
      values: |
        ingressClassResource:
          default: true
        # TODO: enable proxy protocol
        controller:
          kind: DaemonSet
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          service:
            # TODO: use Service .spec.type: NodePort
            type: ClusterIP
          hostPort:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          config:
            allow-snippet-annotations: "true"
            generate-request-id: "true"
