apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    helm:
      releaseName: vault
      valuesObject:
        global:
          enabled: true
          tlsDisable: true

        injector:
          enabled: false

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            pathType: Prefix
            tls:
              - secretName: vault-ingress-tls
                hosts:
                  - vault.mareshq.com
            hosts:
              - host: vault.mareshq.com
                paths:
                  - /

          resources:
            requests:
              memory: 512Mi
              cpu: 400m
            limits:
              memory: 1Gi
              cpu: 400m

          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          livenessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true"
            initialDelaySeconds: 60

          auditStorage:
            enabled: true
            size: 1Gi

          dataStorage:
            enabled: true
            size: 1Gi

          standalone:
            enabled: false

          ha:
            enabled: true
            replicas: 3
            disruptionBudget:
              enabled: true

            raft:
              enabled: true
              setNodeId: true
