kube-prometheus-stack:
  cleanPrometheusOperatorObjectNames: true
  fullnameOverride: "monitoring"

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: hcloud-volumes
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

      additionalScrapeConfigs:
      - job_name: node-exporter-maple
        scheme: http
        static_configs:
        - targets:
          - maple.vxm.cz:9100
          labels:
            vxm_infra: true
            vxm_dedicated: true
            vxm_provider: hetzner
            vxm_server: maple

    ingress:
      enabled: false
      pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-mareshq
        # nginx.ingress.kubernetes.io/auth-url: "https://auth.cloud.mareshq.com/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://auth.cloud.mareshq.com/oauth2/start?rd=$scheme://$host$request_uri"
      hosts:
        - prometheus.cloud.mareshq.com
      paths:
        - /
      tls:
        - hosts:
          - prometheus.cloud.mareshq.com
          secretName: prometheus-tls

    serviceMonitor:
      selfMonitor: true

  grafana:
    enabled: false

  alertmanager:
    enabled: false

  prometheus-node-exporter:
    fullnameOverride: node-exporter

  kube-state-metrics:
    fullnameOverride: kube-state-metrics

node-problem-detector:
  fullnameOverride: node-problem-detector

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true

prometheus-blackbox-exporter:
  fullnameOverride: blackbox-exporter
