apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    foo: AgCTxkKEQcVKMdVqud2S8QRAlh0RsM580PYv9G4cc9eqY73jnhiWnEo3ntlGBF6lwj/oFDxrTsYVzh9+VXak1pCDYTg2jRKgwuEVDUYXutRYruXxlV4QU3BMN+PWhhsorrTr9nbdsIXuwVfUGxTqGUGhmZahqf6lCFpPJu33Cs1co/zK/UF+gMAs1KDG0ScYQHc4EcUeXD64+XZQhdvlKm3JPoF9P88Z/2NnB9b82Ik+SuPtEZk9eFEUgiGjLuyYZUXytEKjkxN15tWR7KVOnQMn1T+U/7JoaAMO+UXNYyzP1CHhb6cFZRfczdiIbbHckxl/J4bu7nTZDoTbPxnDASHooQQiBl1o73n2o98OKYJmyxi/JSAaWiFhiZv9aedVwoJFt3YHUTQ0q9jDjFBVioX7b9F8l1oTKrIvkWvnVO2O35mq3yw2N9cuuEQhcaQiQ9Swp0dklYEDAj9yve8S5451dF8reQm5CL/mRucDAyOiVbqdjS5f0rHcPjzZO9g7pEIcxMBMLcEuuVahpqI0GP9m4Ag/x6RhZR9497QjbibWmjXi74XHrwHLcgFrUYEZEvwh5KCCbp3vIhvidmuw7gIjz09loW3oYnybZZiQmpXAoNDK0dV+w+FyXXaUKyb69enw4Yv2ea833hSflUus4xAPg1iOTwyJ5xLhySc/do/6Hxid9FWKOsEAPC80NlwV7FBxupYLPTDKBOHF/jlM2gvEtbS4FWYn8PsLFDBY9oMJxIIRfG/YbRpGzBKO0r/3HiLjecACUg6pvaXwhE34QPgc
  template:
    metadata:
      creationTimestamp: null
      name: hcloud
      namespace: kube-system

