ingress-nginx:
  controller:
    kind: DaemonSet

    ingressClassResource:
      default: true

    hostPort:
      enabled: true

    service:
      type: ClusterIP

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
