longhorn:
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.cloud.mareshq.com
    tls: true
    tlsSecret: longhorn-tls

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-mareshq
