operator:
  console:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: minio-console-tls
          hosts:
            - console.minio.cloud.mareshq.com
      host: console.minio.cloud.mareshq.com

# tenant:
