minio:
  fullnameOverride: minio

  mode: standalone

  persistence:
    storageClass: longhorn
    size: 200Gi

  DeploymentUpdate:
    type: Delete

  ingress:
    enabled: true

    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-mareshq
      # kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.allow-http: "false"
      # kubernetes.io/ingress.global-static-ip-name: ""
      # nginx.ingress.kubernetes.io/secure-backends: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0

    hosts:
      - minio.cloud.mareshq.com
    tls:
     - secretName: minio-tls
       hosts:
         - minio.cloud.mareshq.com

  consoleIngress:
    enabled: true

    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-mareshq
      # kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.allow-http: "false"
      # kubernetes.io/ingress.global-static-ip-name: ""
      # nginx.ingress.kubernetes.io/secure-backends: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0

    hosts:
      - console.minio.cloud.mareshq.com
    tls:
     - secretName: minio-console-tls
       hosts:
         - console.minio.cloud.mareshq.com
