promtail:
  fullnameOverride: promtail

loki:
  fullnameOverride: loki

  write:
    persistence:
      size: 20Gi
      storageClass: hcloud-volumes

  read:
    persistence:
      size: 20Gi
      storageClass: hcloud-volumes

  singleBinary:
    persistence:
      storageClass: hcloud-volumes

  monitoring:
    # Do not collect the logs of Loki inside Loki
    selfMonitoring:
      enabled: false

      grafanaAgent:
        installOperator: false
