apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-cloud-controller-manager
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/bee/infrastructure/hcloud-cloud-controller-manager
    repoURL: https://github.com/vojtechmares/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
