apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/kubernetes
    repoURL: https://github.com/hetznercloud/csi-driver.git
    targetRevision: v2.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
