apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/bee/infrastructure/monitoring
    repoURL: https://github.com/vojtechmares/gitops.git
    targetRevision: HEAD
    helm:
      skipCrds: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
