apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-mareshq
spec:
  acme:
    email: me+infra@vojtechmares.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-mareshq
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        cloudflare:
          email: iam@vojtechmares.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
