apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: universal-clusterissuer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - cluster: cherry
            url: https://kubernetes.default.svc
          - cluster: lychee
            url: https://172.16.152.1:6443
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{cluster}}-http-clusterissuer"
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: clusterissuer/
        repoURL: https://github.com/vojtechmares/gitops.git
        targetRevision: HEAD
      destination:
        server: "{{url}}"
        namespace: default
