apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: universal-system-upgrade-controller
spec:
  generators:
    - list:
        elements:
          - cluster: cherry
            url: https://kubernetes.default.svc
  syncPolicy:
    applicationsSync: sync
  template:
    metadata:
      name: "{{cluster}}-system-upgrade-controller"
    spec:
      project: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/rancher/system-upgrade-controller.git
        targetRevision: v0.13.1
        path: manifests/
      destination:
        server: "{{url}}"
        namespace: system-upgrade
