apiVersion: v2
name: prometheus-stack
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: kube-prometheus-stack
  version: 39.11.0
  repository: https://prometheus-community.github.io/helm-charts
- name: node-problem-detector
  version: 2.3.1
  repository: https://charts.deliveryhero.io/
- name: prometheus-blackbox-exporter
  version: 7.1.3
  repository: https://prometheus-community.github.io/helm-charts
